# Generated by Django 5.2.7 on 2025-11-09 14:07

import accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioapp',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Imagen JPG/PNG. Máx 2MB.', null=True, upload_to='users/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), accounts.models.validate_file_size_2mb]),
        ),
        migrations.AlterField(
            model_name='usuarioapp',
            name='phone',
            field=models.CharField(blank=True, help_text='Teléfono de contacto (ej: +56912345678)', max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\+?\\d{8,12}$', message='El teléfono debe ser un número válido.')]),
        ),
    ]
