# Generated by Django 5.2.7 on 2025-12-12 16:46

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=40)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre_empresa', models.CharField(db_index=True, max_length=100, verbose_name='Nombre Empresa')),
                ('rut_empresa', models.CharField(max_length=20, unique=True, verbose_name='RUT/NIT')),
                ('email', models.EmailField(max_length=150, unique=True, verbose_name='Email')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('telefono_alternativo', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono Alternativo')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección')),
                ('ciudad', models.CharField(max_length=50, verbose_name='Ciudad')),
                ('region', models.CharField(max_length=50, verbose_name='Región')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('SUSPENDIDO', 'Suspendido')], default='ACTIVO', max_length=10, verbose_name='Estado')),
                ('condiciones_pago', models.CharField(blank=True, max_length=100, null=True, verbose_name='Condiciones de Pago')),
                ('dias_credito', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Días de Crédito')),
                ('monto_credito', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto de Crédito')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre_empresa'],
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre_corto', models.CharField(max_length=5, unique=True, verbose_name='Código (KG, LT)')),
                ('nombre_largo', models.CharField(max_length=50, unique=True, verbose_name='Nombre Completo (Kilogramos, Litros)')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(db_index=True, max_length=35)),
                ('stock_minimo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_maximo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.IntegerField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='insumos', to='inventario.categoria')),
                ('unidad_medida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='insumos_medidos', to='inventario.unidadmedida')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='InsumoLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha_ingreso', models.DateField(db_index=True)),
                ('fecha_expiracion', models.DateField(db_index=True)),
                ('cantidad_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_actual', models.DecimalField(db_index=True, decimal_places=2, max_digits=10)),
                ('bodega', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='inventario.bodega')),
                ('insumo', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='inventario.insumo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes_creados', to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='inventario.proveedor')),
            ],
            options={
                'ordering': ['-fecha_ingreso'],
            },
        ),
        migrations.CreateModel(
            name='OrdenInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_CURSO', 'En Curso'), ('CERRADA', 'Cerrada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=50)),
                ('tipo_orden', models.CharField(choices=[('ENTRADA', 'Entrada de Insumos'), ('SALIDA', 'Salida de Insumos')], default='ENTRADA', max_length=40, verbose_name='Tipo de Orden')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrdenInsumoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cantidad_solicitada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_atendida', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.insumo')),
                ('orden_insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.ordeninsumo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=20)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ubicaciones', to='inventario.bodega')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_generada', models.DateField(db_index=True)),
                ('tipo', models.CharField(default='VENTA', max_length=50)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('detalle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salidas', to='inventario.ordeninsumodetalle')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.insumo')),
                ('insumo_lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.insumolote')),
                ('orden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salidas', to='inventario.ordeninsumo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.ubicacion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField(db_index=True)),
                ('tipo', models.CharField(default='COMPRA', max_length=50)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.insumo')),
                ('insumo_lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.insumolote')),
                ('orden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas', to='inventario.ordeninsumo')),
                ('detalle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas', to='inventario.ordeninsumodetalle')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.ubicacion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AlertaInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('SIN_STOCK', 'Sin Stock (Stock = 0)'), ('BAJO_STOCK', 'Stock Bajo (Stock < Mínimo)'), ('STOCK_EXCESIVO', 'Stock Excesivo (Stock > Máximo)'), ('VENCIMIENTO_PROXIMO', 'Próximo a Vencer')], db_index=True, default='BAJO_STOCK', max_length=50)),
                ('mensaje', models.TextField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alertas', to='inventario.insumo')),
            ],
            options={
                'ordering': ['-fecha', '-id'],
                'indexes': [models.Index(fields=['insumo', 'is_active', 'tipo'], name='inventario__insumo__46f38f_idx'), models.Index(fields=['is_active', 'fecha'], name='inventario__is_acti_9502b6_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='insumolote',
            index=models.Index(fields=['insumo', 'is_active', 'cantidad_actual'], name='inventario__insumo__63ba0b_idx'),
        ),
        migrations.AddIndex(
            model_name='insumolote',
            index=models.Index(fields=['fecha_expiracion', 'is_active'], name='inventario__fecha_e_e8c5a6_idx'),
        ),
        migrations.AddIndex(
            model_name='insumolote',
            index=models.Index(fields=['bodega', 'insumo'], name='inventario__bodega__163f0d_idx'),
        ),
        migrations.AddIndex(
            model_name='insumo',
            index=models.Index(fields=['nombre', 'categoria'], name='inventario__nombre_e00e93_idx'),
        ),
        migrations.AddIndex(
            model_name='insumo',
            index=models.Index(fields=['is_active', 'nombre'], name='inventario__is_acti_27b34d_idx'),
        ),
    ]
