# Generated by Django 5.2.7 on 2025-11-27 17:05

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre_empresa', models.CharField(max_length=100, verbose_name='Nombre Empresa')),
                ('rut_empresa', models.CharField(max_length=20, unique=True, verbose_name='RUT/NIT')),
                ('email', models.EmailField(max_length=150, unique=True, verbose_name='Email')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('telefono_alternativo', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono Alternativo')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección')),
                ('ciudad', models.CharField(max_length=50, verbose_name='Ciudad')),
                ('region', models.CharField(max_length=50, verbose_name='Región')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('SUSPENDIDO', 'Suspendido')], default='ACTIVO', max_length=10, verbose_name='Estado')),
                ('condiciones_pago', models.CharField(blank=True, max_length=100, null=True, verbose_name='Condiciones de Pago')),
                ('dias_credito', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Días de Crédito')),
                ('monto_credito', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto de Crédito')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre_empresa'],
            },
        ),
        migrations.AlterField(
            model_name='insumolote',
            name='bodega',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='inventario.bodega'),
        ),
        migrations.AlterField(
            model_name='insumolote',
            name='insumo',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='inventario.insumo'),
        ),
        migrations.AddField(
            model_name='insumolote',
            name='proveedor',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='inventario.proveedor'),
        ),
    ]
