# Generated by Django 5.2.7 on 2025-12-16 02:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entrada',
            options={'ordering': ['-fecha', '-id']},
        ),
        migrations.AlterModelOptions(
            name='ordeninsumo',
            options={'ordering': ['-fecha', '-id']},
        ),
        migrations.AlterModelOptions(
            name='salida',
            options={'ordering': ['-fecha_generada', '-id']},
        ),
        migrations.AddIndex(
            model_name='entrada',
            index=models.Index(fields=['fecha', 'is_active'], name='inventario__fecha_621a6e_idx'),
        ),
        migrations.AddIndex(
            model_name='entrada',
            index=models.Index(fields=['insumo', 'fecha'], name='inventario__insumo__82da8e_idx'),
        ),
        migrations.AddIndex(
            model_name='entrada',
            index=models.Index(fields=['insumo_lote', 'is_active'], name='inventario__insumo__87684c_idx'),
        ),
        migrations.AddIndex(
            model_name='ordeninsumo',
            index=models.Index(fields=['estado', 'is_active'], name='inventario__estado_b532bf_idx'),
        ),
        migrations.AddIndex(
            model_name='ordeninsumo',
            index=models.Index(fields=['fecha', 'is_active'], name='inventario__fecha_40f77e_idx'),
        ),
        migrations.AddIndex(
            model_name='ordeninsumo',
            index=models.Index(fields=['is_active', 'estado', 'fecha'], name='inventario__is_acti_e29887_idx'),
        ),
        migrations.AddIndex(
            model_name='salida',
            index=models.Index(fields=['fecha_generada', 'is_active'], name='inventario__fecha_g_3c893a_idx'),
        ),
        migrations.AddIndex(
            model_name='salida',
            index=models.Index(fields=['insumo', 'fecha_generada'], name='inventario__insumo__075ccf_idx'),
        ),
        migrations.AddIndex(
            model_name='salida',
            index=models.Index(fields=['insumo_lote', 'is_active'], name='inventario__insumo__724bba_idx'),
        ),
    ]
